/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentationLayer;
import dataTransferObject.*;
import businessLayer.*;
import java.awt.Component;
import java.awt.Image;
import java.sql.*;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.runtime.Debug.id;

/**
 *
 * @author Mamon
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home(){
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnu_DanhMuc = new javax.swing.JMenu();
        mni_QuanLyNguoiDung = new javax.swing.JMenuItem();
        mni_Thoat = new javax.swing.JMenuItem();
        mnu_ChucNang = new javax.swing.JMenu();
        mni_TTKhachHang = new javax.swing.JMenuItem();
        mni_TTMayTinh = new javax.swing.JMenuItem();
        mnu_PhieuMuaHang = new javax.swing.JMenu();
        mni_ChiTietPhieuMua = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Home Computer");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 57, 221));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PHẦN MỀM BÁN MÁY VI TÍNH");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thiet-bi-ban-hang-2.png"))); // NOI18N

        mnu_DanhMuc.setText("Danh Mục");

        mni_QuanLyNguoiDung.setText("Quản Lý Tài Khoản Người Dùng");
        mni_QuanLyNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_QuanLyNguoiDungActionPerformed(evt);
            }
        });
        mnu_DanhMuc.add(mni_QuanLyNguoiDung);

        mni_Thoat.setText("Đăng Xuất");
        mni_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_ThoatActionPerformed(evt);
            }
        });
        mnu_DanhMuc.add(mni_Thoat);

        jMenuBar1.add(mnu_DanhMuc);

        mnu_ChucNang.setText("Chức Năng");

        mni_TTKhachHang.setText("Thông Tin Khách Hàng");
        mni_TTKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_TTKhachHangActionPerformed(evt);
            }
        });
        mnu_ChucNang.add(mni_TTKhachHang);

        mni_TTMayTinh.setText("Thông Tin Máy Tính");
        mni_TTMayTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_TTMayTinhActionPerformed(evt);
            }
        });
        mnu_ChucNang.add(mni_TTMayTinh);

        jMenuBar1.add(mnu_ChucNang);

        mnu_PhieuMuaHang.setText("Phiếu Mua Hàng");
        mnu_PhieuMuaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_PhieuMuaHangActionPerformed(evt);
            }
        });

        mni_ChiTietPhieuMua.setText("Xem chi tiết");
        mni_ChiTietPhieuMua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_ChiTietPhieuMuaActionPerformed(evt);
            }
        });
        mnu_PhieuMuaHang.add(mni_ChiTietPhieuMua);

        jMenuBar1.add(mnu_PhieuMuaHang);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mni_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_ThoatActionPerformed
       
        int tb = JOptionPane.showConfirmDialog(rootPane, "Thoát phiên làm việc?","Cảnh Báo", JOptionPane.YES_NO_OPTION);               
        if (tb == JOptionPane.YES_OPTION) {
            Login lg = new Login();
            this.dispose();
            lg.setVisible(true);
        }
        else
            return;               
    }//GEN-LAST:event_mni_ThoatActionPerformed

    private void mni_QuanLyNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_QuanLyNguoiDungActionPerformed
        ThongTinNhanVien ttnv = new ThongTinNhanVien(this, rootPaneCheckingEnabled);
        ttnv.setVisible(true);
    }//GEN-LAST:event_mni_QuanLyNguoiDungActionPerformed

    
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
    }//GEN-LAST:event_formComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
    }//GEN-LAST:event_formWindowOpened

    private void mni_TTKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_TTKhachHangActionPerformed
        // TODO add your handling code here:
        
        ThongTinKhachHang ttkhachhang = new ThongTinKhachHang(this, rootPaneCheckingEnabled);             
        ttkhachhang.setVisible(true);
    }//GEN-LAST:event_mni_TTKhachHangActionPerformed

    private void mni_TTMayTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_TTMayTinhActionPerformed
        
        ThongTinMayTinh ttmt = new ThongTinMayTinh(this, rootPaneCheckingEnabled);
        ttmt.setVisible(true);
    }//GEN-LAST:event_mni_TTMayTinhActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Login lg = new Login();
        this.dispose();
        lg.setVisible(true);                    
    }//GEN-LAST:event_formWindowClosing

    private void mnu_PhieuMuaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_PhieuMuaHangActionPerformed
        
    }//GEN-LAST:event_mnu_PhieuMuaHangActionPerformed

    private void mni_ChiTietPhieuMuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_ChiTietPhieuMuaActionPerformed
        ThongTinPhieuBan ttpb = new ThongTinPhieuBan(null, rootPaneCheckingEnabled);
        ttpb.setVisible(true); 
    }//GEN-LAST:event_mni_ChiTietPhieuMuaActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mni_ChiTietPhieuMua;
    private javax.swing.JMenuItem mni_QuanLyNguoiDung;
    private javax.swing.JMenuItem mni_TTKhachHang;
    private javax.swing.JMenuItem mni_TTMayTinh;
    private javax.swing.JMenuItem mni_Thoat;
    private javax.swing.JMenu mnu_ChucNang;
    private javax.swing.JMenu mnu_DanhMuc;
    private javax.swing.JMenu mnu_PhieuMuaHang;
    // End of variables declaration//GEN-END:variables
}
